stages:
  - build
  - test

build-job:
  stage: build
  script:
    - ./gradlew :stub:jar

unit-test-job:
  stage: test
  script:
    - ./gradlew test

lint-test-job:
  stage: test
  script:
    - ./gradlew ktlintCheck
